# Generated by Django 4.2.9 on 2024-04-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_featuremapping_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuremapping',
            old_name='request',
            new_name='requests',
        ),
    ]
