# Generated by Django 4.2.9 on 2024-04-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_rename_request_featuremapping_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuremapping',
            name='requests',
        ),
    ]
